// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsxyRGj52TP6r7Nw449HuXz4WeOAJ7lLI',
    appId: '1:148905427671:web:26994b88028c55008b6692',
    messagingSenderId: '148905427671',
    projectId: 'final-project-4aea9',
    authDomain: 'final-project-4aea9.firebaseapp.com',
    storageBucket: 'final-project-4aea9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtoBwN77wd3T6SmqdooqNp3xcSAIauG54',
    appId: '1:148905427671:android:24c3874581e80c228b6692',
    messagingSenderId: '148905427671',
    projectId: 'final-project-4aea9',
    storageBucket: 'final-project-4aea9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjPtZ2iZe4GJHOd_hD0qIg9dvg_Rb6NNY',
    appId: '1:148905427671:ios:d4897bf3571525948b6692',
    messagingSenderId: '148905427671',
    projectId: 'final-project-4aea9',
    storageBucket: 'final-project-4aea9.appspot.com',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjPtZ2iZe4GJHOd_hD0qIg9dvg_Rb6NNY',
    appId: '1:148905427671:ios:d4897bf3571525948b6692',
    messagingSenderId: '148905427671',
    projectId: 'final-project-4aea9',
    storageBucket: 'final-project-4aea9.appspot.com',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsxyRGj52TP6r7Nw449HuXz4WeOAJ7lLI',
    appId: '1:148905427671:web:dd14e2a3eb09b09b8b6692',
    messagingSenderId: '148905427671',
    projectId: 'final-project-4aea9',
    authDomain: 'final-project-4aea9.firebaseapp.com',
    storageBucket: 'final-project-4aea9.appspot.com',
  );
}
